### ISSUE TITLE
无法拉取镜像

### ISSUE THREAD

**Issue by emengweb** [zuisong/gemini-openai-proxy#13]
测试了对最新的0.8和旧版本的0.6镜像都无法拉取，在多台服务器测试均提示 manifest unknown

ghcr.io域名下的其他镜像可正常拉取，这个情况很奇怪，不知道要如何解决

**Comment by zuisong** [comment]
我重新运行ci推送了镜像。现在应该好了
---
这个问题或许是github 生成了许多没有tag的镜像， 镜像之间可能有关联，删掉那些镜像之后，有tag的也没法pull了

我会删掉这个任务， 后面应该就不会有这个问题了
https://github.com/zuisong/gemini-openai-proxy/blob/main/.github/workflows/delete-untag-image.yaml

**Comment by zuisong** [comment]
相关链接：
https://github.com/Chizkiyahu/delete-untagged-ghcr-action/issues/22
https://github.com/orgs/community/discussions/45779

**Comment by emengweb** [comment]
感谢！已经可以正常拉取镜像并使用了！
