### ISSUE TITLE
Deno deployment not working

### ISSUE THREAD

**Issue by TarekMSayed** [zuisong/gemini-openai-proxy#21]
I installed a Deno deployment 
https://github.com/zuisong/gemini-openai-proxy/blob/main/dist/main_deno.mjs
put I am receiving an error
```json
{"id":"chatcmpl-abc123","object":"chat.completion","created":1708722674499,"model":"gpt-3.5-turbo","choices":[{"message":{"role":"assistant","content":"[GoogleGenerativeAI Error]: Error fetching from https://generativelanguage.googleapis.com/v1/models/gemini-pro:generateContent: [400 Bad Request] User location is not supported for the API use."},"logprobs":null,"finish_reason":"stop","index":0}]}
```

**Comment by zuisong** [comment]
The prompt says that gemini is not supported in your region, you may need to use a proxy to a region that supports gemini.

see #4 

https://ai.google.dev/available_regions#available_regions

**Comment by TarekMSayed** [comment]
@zuisong I am in Egypt and my country in the list

**Comment by zuisong** [comment]
You may now use the instance I have deployed. `https://gemini-openai-proxy.zuisong.workers.dev/v1/chat/completions`

**Comment by TarekMSayed** [comment]
Thanks, @zuisong, it works with your deployed instance 
what is the difference, Sorry didn't got what you refer to it here https://github.com/zuisong/gemini-openai-proxy/issues/4
it is in Chinese.

**Comment by zuisong** [comment]
> Cloudflare Workers runs on Cloudflare’s global network in hundreds of cities worldwide

cf worker runs randomly on servers in different regions and may run in regions not supported by google gemini (the same is true for deno deploy, except that deno deploy is usable in China).

@TarekMSayed 
So the best way is to deploy a service yourself, the readme has a docker deployment script.

**Comment by TarekMSayed** [comment]
Thanks, @zuisong
