### ISSUE TITLE
[需求] 切換為 v1beta

### ISSUE THREAD

**Issue by bestpika** [zuisong/gemini-openai-proxy#22]
是否能夠在執行時增加參數切換為 v1beta？

**Comment by zuisong** [comment]
https://github.com/google/generative-ai-js/blob/d9c3f4d421100b5656d63e084ca93e418d00bf07/packages/main/src/requests/request.ts#L23

For the current deployed version, the only way to achieve this is to modify the v1 constant in the google sdk to be v1beta.

---

And we can switch to the REST API method without using the Google SDK to use the v1beta version of the API.

**Comment by bestpika** [comment]
So does this feature be merged into the main branch and then switched parameters when executed?
Or will it only be on the "issue22" branch?

**Comment by zuisong** [comment]
it will be merged to the main branch. 

I'm thinking of a convenient way to pass parameters. Currently, it seems that parameters can only be passed through the apikey.

**Comment by zuisong** [comment]
You can now use the `v1beta` version of the API by adding #useBeta at the end of the API key.

```shell
curl http://localhost:8000/v1/chat/completions \
  -H "Authorization: Bearer $YOUR_GEMINI_API_KEY#useBeta" \
  -H "Content-Type: application/json" \
  -d '{
  "model": "gpt-3.5-turbo",
  "messages": [{"role": "user", "content": "Hello"}],
  "temperature": 0.7,"stream":true
  }'
```

**Comment by bestpika** [comment]
It looks like it's working well.

**Comment by zuisong** [comment]
with #41 merged. 

The current default API version is v1beta.
