### ISSUE TITLE
请问转发后，是否可以用openai调用tools的方式直接调用gemin的tools

### ISSUE THREAD

**Issue by fatwang2** [zuisong/gemini-openai-proxy#24]
我看项目里有部分function calling的代码，想了解下是也做了这部分处理逻辑吗

**Comment by zuisong** [comment]
暂时是不支持function calling的

周末的时候我可以看一下怎么适配 function calling

**Comment by zuisong** [comment]
在不是流式响应的情况下，支持了 function calling
