### ISSUE TITLE
部署到Cloudflare worker，出现Internal Server Error

### ISSUE THREAD

**Issue by crosspacific** [zuisong/gemini-openai-proxy#25]
自己部署到Cloudflare worker后，无论是使用workers.dev，还是自定义域名，总是出现Internal Server Error 错误。
![20240307155136](https://github.com/zuisong/gemini-openai-proxy/assets/48462348/039346e3-34eb-4dcb-95b7-2d3dfcfaf21a)

使用项目提供的网址，出现429错误。
![20240307164255](https://github.com/zuisong/gemini-openai-proxy/assets/48462348/f65ba527-8092-4c70-9eae-498b968a22e5)

不使用转换，在其他软件直接使用gemini key，正常。

**Comment by zuisong** [comment]
- Internal Server Error 服务器错误这个会修复
---
- 429错误可能是 `cf worker` 被 google 限流了

**Comment by zuisong** [comment]
<img width="2002" alt="image" src="https://github.com/zuisong/gemini-openai-proxy/assets/19145952/9947b1c8-1d9b-41fb-99b9-e779314441c2">


我刚刚试了一下，现在部署上去是可以用的

**Comment by crosspacific** [comment]
谢谢。
重新部署后，网页正常。
![20240307175225](https://github.com/zuisong/gemini-openai-proxy/assets/48462348/6e6d8c36-0d46-46c5-8d4a-7a568124e1ee)

psot出现500错误

![20240307175608](https://github.com/zuisong/gemini-openai-proxy/assets/48462348/4338b8be-9104-442d-9010-c2cf188e9c89)

在服务器中使用，还是出现429错误，

![20240307175740](https://github.com/zuisong/gemini-openai-proxy/assets/48462348/2f5d9cc6-4eb7-4320-b2ca-b1be77a86bb6)

**Comment by zuisong** [comment]
嗯嗯额，你的apikey没打码的

**Comment by crosspacific** [comment]
> 在本地拉下来这个插件的代码，同时利用 chrome devtool 一步步的 debug, 最终发现是这个插件的这里的逻辑导致的 https://github.com/openai-translator/openai-translator/blob/5f8730e59143ab144413cc18a3b42e49164ecd5a/src/common/engines/abstract-openai.ts#L146
> 
> openai 的响应，`finish_reason":"stop"` 对应的那条消息是没有响应正文的，之前的逻辑没有和 openai 的保持一致，出现了不兼容的情况
> 
> 我已经修改了代理的代码，现在和openai保持一致了， 现在可以正常使用了

非常感谢。已经可以使用了。谢谢你的项目。

**Comment by XYZliang** [comment]
> > 在本地拉下来这个插件的代码，同时利用 chrome devtool 一步步的 debug, 最终发现是这个插件的这里的逻辑导致的 https://github.com/openai-translator/openai-translator/blob/5f8730e59143ab144413cc18a3b42e49164ecd5a/src/common/engines/abstract-openai.ts#L146
> > openai 的响应，`finish_reason":"stop"` 对应的那条消息是没有响应正文的，之前的逻辑没有和 openai 的保持一致，出现了不兼容的情况
> > 我已经修改了代理的代码，现在和openai保持一致了， 现在可以正常使用了
> 
> 非常感谢。已经可以使用了。谢谢你的项目。

您好，请问您是如何部署到 cf？是将https://github.com/zuisong/gemini-openai-proxy/blob/main/dist/main_cloudflare-workers.mjs复制过去吗？

**Comment by XYZliang** [comment]
> @XYZliang 是的，直接复制过去就可以使用了

比较头疼的是经常出现User location is not supported for the API use.

**Comment by crosspacific** [comment]
> > @XYZliang 是的，直接复制过去就可以使用了
> 
> 比较头疼的是经常出现User location is not supported for the API use.

因为从大陆连接cloudflare，会走香港的服务器，而香港是不支持Gemini的。挂代理使用就可以了。

**Comment by zuisong** [comment]
@crosspacific  @XYZliang  
https://github.com/zuisong/gemini-openai-proxy#deno-deploy
可以尝试一下 deno deploy， 目前是可以直连使用的

**Comment by XYZliang** [comment]
> 会走香港的服务器

感谢您的建议，确实是可以用，但是不知道为什么deno的自定义Domains，curl 测试正常但是我使用的软件报错（bob，macOS下的翻译软件），只能使用提供的.deno.dev域名，但是问题不大，希望能长久使用哈哈哈

**Comment by XYZliang** [comment]
> > > @XYZliang 是的，直接复制过去就可以使用了
> > 
> > 
> > 比较头疼的是经常出现User location is not supported for the API use.
> 
> 因为从大陆连接cloudflare，会走香港的服务器，而香港是不支持Gemini的。挂代理使用就可以了。

是的，cf 这个设定太难受了，尝试在里面加了一些请求美国网站的动作，智能部署还是不成功

**Comment by crosspacific** [comment]
这个问题又出现了😂

**Comment by zuisong** [comment]
@crosspacific  我刚刚去试了一下，刚刚下载的插件，配置后可以正常翻译呀

**Comment by crosspacific** [comment]
> [@crosspacific](https://github.com/crosspacific) 我刚刚去试了一下，刚刚下载的插件，配置后可以正常翻译呀

好的，我再试试。 谢谢。
