### ISSUE TITLE
建议 gemini 返回错误时，proxy api 也返回错误消息，而不是把错误信息封装成正确消息返回

### ISSUE THREAD

**Issue by qiuxiang** [zuisong/gemini-openai-proxy#29]
有些应用会缓存成功的 openai 调用结果，如果 gemini 报错以正常消息返回，就会被缓存下来。

**Comment by zuisong** [comment]
嗯嗯，这个问题确实存在，但也有一些应用不会反馈把错误信息给用户，gemini报错非常频繁，原因多种多样，直接报错的话，用户会以为代理没生效或者代理有问题

或许可以做成一个可配置项来做

**Comment by qiuxiang** [comment]
gemini 报错频繁一方面是 gemini 现在会根据请求 headers 判别使用场景，对于某些使用场景比如（immersive translate），gemini 现在是禁用的。所以我就想把 gemini 代理成 openai，绕过 gemini 的检测。

另一方面是 gemini 现在限流也比较严，调用频率不能太高，高了必报错。

**Comment by zuisong** [comment]
gemini 的报错也分成 `可恢复` 的 和 `不可恢复` 的 两类， 目前无法区分这两类，
直接报错不是一个好的方案，综合考虑，决定还是维持现状，不修改了

---
- 参考一下 [one-api](https://github.com/songquanpeng/one-api) 的做法, 看不到任何详细的错误信息，


	```go
	    if err != nil {
	        return openai.ErrorWrapper(err, "unmarshal_response_body_failed", http.StatusInternalServerError), nil
	    }
	    if len(geminiResponse.Candidates) == 0 {
	        return &model.ErrorWithStatusCode{
	            Error: model.Error{
	                Message: "No candidates returned",
	                Type:    "server_error",
	                Param:   "",
	                Code:    500,
	            },
	            StatusCode: resp.StatusCode,
	        }, nil
	```
	
	https://github.com/songquanpeng/one-api/blob/4ae311e964ba9a3a838b789ca7d21b9504cfff9e/relay/channel/gemini/main.go#L272-L284


---
- ChatGPTNextWeb 也是一样的，报错信息直接忽略掉
  https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/blob/3ba984d09e57cd64ca8e7c28bb15be00e0a357fa/app/client/platforms/openai.ts#L228-L241
