### ISSUE TITLE
一个功能需求

### ISSUE THREAD

**Issue by Stanley-baby** [zuisong/gemini-openai-proxy#3]
希望可以转换为 CF worker部署，这样就不需要 docker 了，而且更加方便。

**Comment by zuisong** [comment]
目前可以通过deno deploy部署，每个月有一百万请求数，对于个人使用基本可以算免费的 https://deno.com/deploy

CF worker 这几天我会看一下相关文档，会尽快适配

**Comment by Stanley-baby** [comment]
搞定了？大佬

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: zuisong ***@***.***>
发送时间: Friday, January 19, 2024 12:15:19 AM
收件人: zuisong/gemini-openai-proxy ***@***.***>
抄送: Stanley-baby ***@***.***>; Author ***@***.***>
主题: Re: [zuisong/gemini-openai-proxy] 一个功能需求 (Issue #3)


Closed #3<https://github.com/zuisong/gemini-openai-proxy/issues/3> as completed via 2312338<https://github.com/zuisong/gemini-openai-proxy/commit/2312338766fc9d130c8f8dacb836db1f5d22945e>.

―

**Comment by zuisong** [comment]
https://github.com/zuisong/gemini-openai-proxy/blob/main/cloudflare-workers/main_cloudflare-workers.js

想从源码自己构建的话 可以用 `bun install && bun run rollup.config.cloudflare-workers.ts` 构建出来

**Comment by zuisong** [comment]
实测可以

<img width="821" alt="image" src="https://github.com/zuisong/gemini-openai-proxy/assets/19145952/15450b7f-ba22-4fcc-8d6f-edeaf6352411">

**Comment by Stanley-baby** [comment]
我尝试一下，workers就用的js

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: zuisong ***@***.***>
发送时间: Friday, January 19, 2024 12:16:57 AM
收件人: zuisong/gemini-openai-proxy ***@***.***>
抄送: Stanley-baby ***@***.***>; Author ***@***.***>
主题: Re: [zuisong/gemini-openai-proxy] 一个功能需求 (Issue #3)


https://github.com/zuisong/gemini-openai-proxy/blob/main/cloudflare-workers/main_cloudflare-workers.js

想从源码自己构建的话 可以用 bun install && bun run rollup.config.cloudflare-workers.ts 构建出来

―

**Comment by Stanley-baby** [comment]
好哒    我明天尝试一下，然后反馈🥳

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: Shao Stanley ***@***.***>
发送时间: Friday, January 19, 2024 12:18:31 AM
收件人: zuisong/gemini-openai-proxy ***@***.***>; zuisong/gemini-openai-proxy ***@***.***>
抄送: Author ***@***.***>
主题: Re: [zuisong/gemini-openai-proxy] 一个功能需求 (Issue #3)

我尝试一下，workers就用的js

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: zuisong ***@***.***>
发送时间: Friday, January 19, 2024 12:16:57 AM
收件人: zuisong/gemini-openai-proxy ***@***.***>
抄送: Stanley-baby ***@***.***>; Author ***@***.***>
主题: Re: [zuisong/gemini-openai-proxy] 一个功能需求 (Issue #3)


https://github.com/zuisong/gemini-openai-proxy/blob/main/cloudflare-workers/main_cloudflare-workers.js

想从源码自己构建的话 可以用 bun install && bun run rollup.config.cloudflare-workers.ts 构建出来
