### ISSUE TITLE
cloudflare具体的部署步骤是什么？

### ISSUE THREAD

**Issue by shwangdev** [zuisong/gemini-openai-proxy#34]
如题。 能详细介绍下怎么在cloudflare上部署这个worker吗？

**Comment by zuisong** [comment]
https://github.com/zuisong/gemini-openai-proxy/raw/main/dist/main_cloudflare-workers.mjs

1. 新建一个 cf worker
2. 拷贝上面这个文件的内容
3. 拷贝到编辑框里
4. 保存
