### ISSUE TITLE
能否解决 Gemini 地区限制.

### ISSUE THREAD

**Issue by sacanods** [zuisong/gemini-openai-proxy#4]
gemini 只在一些[语言和地区提供](https://ai.google.dev/available_regions).
我收到限制地区的错误.

```
Error: [GoogleGenerativeAI Error]:  
Error fetching from https://generativelanguage.googleapis.com/v1/models/gemini-pro:streamGenerateContent?alt=sse: 
[400 Bad Request] User location is not supported for the API use. 
```

部署在 workers 和 deno 的服务器上应该在 gemini 提供的地区内.
能否像[azure-openai-proxy](https://github.com/diemus/azure-openai-proxy)这个项目一样解决限制地区的问题.

谢谢!

**Comment by zuisong** [comment]
这个是由于  workers 和 deno deploy 会自动 负载均衡到用户请求地址所在的地区相近的服务器

从大陆地区访问时， 会走香港的网络， 香港不再 gemini 支持的地区上， 所以会提示地区不支持

cf workers 文档 <https://developers.cloudflare.com/workers/reference/how-workers-works/>

deno deploy 文档 <https://deno.com/blog/the-future-of-web-is-on-the-edge>


---
看了一下cf的配置， 可以尝试配置这个， 或许可以解决这个问题

<img width="1442" alt="image" src="https://github.com/zuisong/gemini-openai-proxy/assets/19145952/c93b746d-7634-4d48-9143-7a2c0113b8cf">

**Comment by zuisong** [comment]
我刚刚试了一下 deno deploy 好像是可以不用翻墙了，不知道稳定不

最好的办法还是自己挂梯子 🤣

**Comment by liyuu-u** [comment]
我把Gemini api部署在vercel上然后用一个国内能访问的个人域名定向到vercel生成的项目上，可以无梯子访问但是最近只能在手机上使用了，用pc端浏览器访问就会出现User location is not supported for the API use without a billing account linked.也不知道是为什么

**Comment by mirrows** [comment]
> 我把Gemini api部署在vercel上然后用一个国内能访问的个人域名定向到vercel生成的项目上，可以无梯子访问但是最近只能在手机上使用了，用pc端浏览器访问就会出现User location is not supported for the API use without a billing account linked.也不知道是为什么

+1 之前我都可以正常访问的，后面就不行了，也是报的User location is not supported for the API use

**Comment by zuisong** [comment]
@mirrows @liyuu-u  
是不是要检查一下 vercel 部署的区域呢？
对于区域限制，从代码上是无法解决的，可以在这里互相交流经验。
我一直使用deno deploy，目前没有遇到区域限制问题。
