### ISSUE TITLE
爬虫访问需要处理吗

### ISSUE THREAD

**Issue by manjieqi** [zuisong/gemini-openai-proxy#46]
![image](https://github.com/zuisong/gemini-openai-proxy/assets/40858189/1453f05c-eb5d-41aa-98ff-43859b3bfded)

看见日志里面有这些访问，会有影响吗，还是需要加一个屏蔽爬虫的？

**Comment by zuisong** [comment]
这个不是爬虫访问的，应该是通过浏览器访问主页留下的，可以不处理

**Comment by manjieqi** [comment]
好的，thank you！
