### ISSUE TITLE
Not real streaming output

### ISSUE THREAD

**Issue by Quilljou** [zuisong/gemini-openai-proxy#56]
I tried to deploy it to CF workers. I set it to stream output. But the result seems to be not streaming, All result output when the request ends on the user end. Anything wrong with my operation

**Comment by zuisong** [comment]
see https://github.com/zuisong/gemini-openai-proxy/pull/55

A redeployment should restore it.

**Comment by Quilljou** [comment]
Thanks.
Btw How do I bypass the wall in the NodeJS project even though I opened the ClashX global proxy? It reports 
```
"delta": {
                "role": "assistant",
                "content": "[GoogleGenerativeAI Error]: Error fetching from google -> [400 Bad Request] User location is not supported for the API use."
            },
```

**Comment by zuisong** [comment]
这一块我没有实际经验，可以尝试 tun模式， 

代码里设置代理的话，这篇文章或许对你有帮助 https://learn.microsoft.com/en-us/microsoft-cloud/dev/dev-proxy/how-to/use-dev-proxy-with-nodejs
