### ISSUE TITLE
error sending request for url 

### ISSUE THREAD

**Issue by anyshu** [zuisong/gemini-openai-proxy#64]
The reponse returned error like below, the base_url is expired？

{"id":"chatcmpl-abc123","object":"chat.completion","created":1721044629,"model":"gpt-4-turbo-preview","choices":[{"message":{"role":"assistant","content":"[GoogleGenerativeAI Error]: Error fetching from google -> error sending request for url (https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-pro-latest:streamGenerateContent?key=xxxxxxxxxxxxxxxxxxxk&alt=sse): error trying to connect: tcp connect error: Cannot assign requested address (os error 99)"},"finish_reason":"stop","index":0,"logprobs":null}]}

**Comment by zuisong** [comment]
Can you access this address? 
You can try to run this.
```shell
ping generativelanguage.googleapis.com
```
