### ISSUE TITLE
please support ask from files for gemini flash (images,videos,pdf's)

### ISSUE THREAD

**Issue by bugbounted** [zuisong/gemini-openai-proxy#75]
hi [PublicAffairs](https://github.com/PublicAffairs)
please support ask from files (images,media,pdf) & put sample in readme.md
waiting for your repsonse
regards

**Comment by zuisong** [comment]
You can do it this way.


<img width="1672" alt="image" src="https://github.com/user-attachments/assets/8fea582c-c6ce-41a1-925a-63141d3db270">
