### ISSUE TITLE
关于safety settings

### ISSUE THREAD

**Issue by noangel2014** [zuisong/gemini-openai-proxy#8]
你好，这个程序非常方便。不过我发现了一个小问题。Gemini api 有一个safety settings。不知道你有没有处理

我测试的时候，输出总是blockReason': 'SAFETY'。非常蛋疼

**Comment by zuisong** [comment]
方便给一个重现案例吗？
暂时不确定能不能避过去，需要去看一下文档

**Comment by zuisong** [comment]
默认设置是 `屏蔽部分`， 我已经修改成了 `全部不屏蔽`


https://ai.google.dev/docs/safety_setting_gemini#safety-settings


<img width="974" alt="image" src="https://github.com/zuisong/gemini-openai-proxy/assets/19145952/f43d1e71-eba1-4dbb-a032-89827cf81ae1">

**Comment by zuisong** [comment]
google gemini api 不支持设置某些分类, 所以之前的代码回滚了。 现在应该可以了
