### ISSUE TITLE
最近通过lss233/chatgpt-mirai-qq-bot项目使用API时出现了empty text parameter

### ISSUE THREAD

**Issue by HoshinoDesu** [zuisong/gemini-openai-proxy#83]
这可能是什么问题导致的？是近一段时间突然出现的，在这之前调用完全正常
`[GoogleGenerativeAI Error]: Error fetching from google -> [400 Bad Request] Unable to submit request because it has an empty text parameter. Add a value to the parameter and try again. Learn more: https://cloud.google.com/vertex-ai/generative-ai/docs/model-reference/gemini`

**Comment by zuisong** [comment]
可以附上请求参数吗？

**Comment by ybhgl** [comment]
> 可以附上请求参数吗？

同样的报错

**Comment by zuisong** [comment]
我已经发布了一个修复版本
感谢 @ybhgl 提供的复现示例

<img width="785" alt="image" src="https://github.com/user-attachments/assets/747f7bcb-c732-46ea-b210-6b2124e82e7f">

**Comment by zuisong** [comment]
@HoshinoDesu  我已经提交了一个修复版本了，现在还有这个问题吗？

**Comment by zuisong** [comment]
@HoshinoDesu 
你可以试一下两天前的修复版本吗？  我没有发布新版本，直接使用 main 分支的代码呢

**Comment by zuisong** [comment]
应该是 gemini api 最近有变化， api 之前是不允许连续出现两个 user 类型的消息的， 所以之前代理的时候插入了空消息， 我刚刚测试了一下，这些限制现在取消了，同时禁止发送空消息给gemini了， 所以最近报错了
