### ISSUE TITLE
404 Page Not Found

### ISSUE THREAD

**Issue by Michal-Mikolas** [zuisong/gemini-openai-proxy#84]
Whenever I open "http://localhost:8000/v1/chat/completions" it shows error: 

```
404 Page Not Found
```

However the server is running, because when I access "http://localhost:8000" it shows this: 

```
    Hello Gemini-OpenAI-Proxy from deno! 
    
    You can try it with:
    
    curl http://localhost:8000/v1/chat/completions \
    -H "Authorization: Bearer $YOUR_GEMINI_API_KEY" \
    -H "Content-Type: application/json" \
    -d '{
        "model": "gpt-3.5-turbo",
        "messages": [{"role": "user", "content": "Hello"}],
        "temperature": 0.7
    }'
```

**Comment by zuisong** [comment]
This is a server-side interface, and this project does not provide a web interface 

You can use this project https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web as a front-end to use this project.
